package com.springsecurity.demo.User;

public enum Permission {
  REGISTER_ONE_USER,
  READ_ONE_USER,
  READ_ALL_USER,
  UPDATE_USER,
  CHANGE_USER_STATUS,
  DELETE_USER,
  CREATE_SUPPLIER,
  READ_ALL_SUPPLIER,
  READ_ONE_SUPPLIER,
  UPDATE_SUPPLIER,
  DELETE_SUPPLIER,
  CREATE_MATERIALS,
  READ_ALL_MATERIALS,
  READ_ONE_MATERIALS,
  UPDATE_MATERIALS,
  DELETE_MATERIALS,
}
