package com.springsecurity.practica.User;

public enum Permission {
  CREATE_SUPPLIER,
  READ_ALL_SUPPLIER,
  READ_ONE_SUPPLIER,
  UPDATE_SUPPLIER,
  DELETE_SUPPLIER,
  CREATE_MATERIALS,
  READ_ALL_MATERIALS,
  READ_ONE_MATERIALS,
  UPDATE_MATERIALS,
  DELETE_MATERIALS,
}
